# Project
title: 심철환의 개발 공부
description: 심철환의 개발 공부

# Author
author: 심철환
email: a@akaiv.com
github_username: s10n

# Configuration
baseurl: /study
permalink: /:title
kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - node_modules
  - assets

sass:
  style: :compressed

lang: ko
timezone: Asia/Seoul

collections:
  studies:
    output: true
    permalink: /study/:path/

defaults:
  - scope:
      path: ""
      type: studies
    values:
      layout: study
